# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/test_convert/',
                'doc_host': 'https://dmitryhits.github.io',
                'git_url': 'https://github.com/muellerzr/test_convert/tree/master/',
                'lib_path': 'test_convert'},
  'syms': {'test_convert.test': {'test_convert.test.testing_code': ('test.html#testing_code', 'test_convert/test.py')}}}
